name: Build and Release Missions Log

on:
  push:
    branches:
      - test-installer

permissions:
    contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download the code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt 6.10
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        cache: true

    - name: Prepare the build files
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build the application
      run: cmake --build build --config Release

    - name: Stage files for Inno Setup
      run: cmake --install build --config Release --prefix "${{ github.workspace }}/stage"

    - name: Compile Inno Setup Script
      run: iscc installer.iss

    - name: Publish to GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: build-${{ github.sha }}
            name: "Missions Log Build (${{ github.sha }})"
            files: Output/MissionsLog-Installer.exe